### ISSUE TITLE
放到popupwindow 中使用报错

### ISSUE THREAD

**Issue by Arthurshen98** [AigeStudio/DatePicker#70]
总报下标越界，奇葩了
ava.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                          at cn.aigestudio.datepicker.bizs.calendars.DPCNCalendar.getFestivalG(DPCNCalendar.java:216)
                                                                          at cn.aigestudio.datepicker.bizs.calendars.DPCNCalendar.buildMonthL(DPCNCalendar.java:137)
                                                                          at cn.aigestudio.datepicker.bizs.calendars.DPCNCalendar.buildMonthFestival(DPCNCalendar.java:107)
                                                                          at cn.aigestudio.datepicker.bizs.calendars.DPCManager.buildDPInfo(DPCManager.java:177)
                                                                          at cn.aigestudio.datepicker.bizs.calendars.DPCManager.obtainDPInfo(DPCManager.java:154)
                                                                          at cn.aigestudio.datepicker.views.MonthView.draw(MonthView.java:314)
                                                                          at cn.aigestudio.datepicker.views.MonthView.onDraw(MonthView.java:280)
                                                                          at android.view.View.draw(View.java:14517)

**Comment by TonyZanyar** [comment]
我也遇到了，好奇怪

**Comment by TonyZanyar** [comment]
要执行：
picker.setDate(2015, 7);
随便个月份吧

**Comment by SNXJ** [comment]
我在dialog里使用已经 picker.setDate(2015, 7);
会报空指针，（如下）
 
  java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.aigestudio.datepicker.views.DatePicker.setDate(int, int)' on a null object reference

但是dataPick对象不为空，如果我对dataPick对象判空   if 判断后就报错（如下）

ava.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
at cn.aigestudio.datepicker.bizs.calendars.DPCNCalendar.getFestivalG(DPCNCalendar.java:216)
